apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: python-course-demo
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/dingwencheng9/python-fullstack-course.git
    targetRevision: main
    path: extensions/k8s-deepening/helm/python-course-demo
  destination:
    server: https://kubernetes.default.svc
    namespace: python-course-demo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
