apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: python-course-demo
  namespace: python-course-demo
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: python-course.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: python-course-demo
                port:
                  name: http
