apiVersion: v1
kind: Service
metadata:
  name: python-course-demo
  namespace: python-course-demo
  labels:
    app.kubernetes.io/name: python-course-demo
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: python-course-demo
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
